# Generated by Django 3.2.13 on 2022-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220529_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_am',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='name_or',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='name_tg',
            field=models.CharField(default='', max_length=255),
        ),
    ]
