# Generated by Django 3.2 on 2023-08-24 19:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_blogtexttranslation_blog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abouttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='abouttranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='blog',
        ),
        migrations.AlterUniqueTogether(
            name='blogtagtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blogtagtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='blogtexttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blogtexttranslation',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogtexttranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='contacttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contacttranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='blogtranslation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogtranslation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogtranslation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='descricption',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='AboutTranslation',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
        migrations.DeleteModel(
            name='BlogTagTranslation',
        ),
        migrations.DeleteModel(
            name='BlogText',
        ),
        migrations.DeleteModel(
            name='BlogTextTranslation',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactTranslation',
        ),
    ]
