# Generated by Django 3.2 on 2023-08-24 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20230824_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtranslation',
            old_name='descricption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
